# Generated by Django 4.1.2 on 2022-12-26 14:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=100)),
                ('cliente_telefone', models.CharField(default=0, max_length=10)),
                ('cliente_email', models.CharField(default=0, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.TextField(max_length=255)),
                ('fabricante', models.CharField(default=0, max_length=100)),
                ('modelo', models.CharField(default=0, max_length=100)),
                ('ano_fab', models.CharField(default=0, max_length=4)),
                ('cor', models.CharField(default=0, max_length=50)),
                ('placa', models.CharField(default=0, max_length=7)),
                ('valor', models.FloatField()),
                ('pago', models.BooleanField(default=False)),
                ('data', models.DateField(default=datetime.datetime.now)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
            ],
            options={
                'ordering': ['servico'],
            },
        ),
    ]
