# Generated by Django 4.1.2 on 2022-12-31 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, null=True, verbose_name='valor'),
        ),
    ]
