# Generated by Django 4.1.2 on 2023-01-03 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_servico_valor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servico',
            options={'ordering': ['data']},
        ),
    ]
