# Generated by Django 4.1.2 on 2023-01-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_alter_cliente_cliente_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cliente_email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente_telefone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='servico',
            name='ano_fab',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='servico',
            name='cor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='servico',
            name='fabricante',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servico',
            name='modelo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servico',
            name='placa',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='servico',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='valor'),
        ),
    ]
