# Generated by Django 4.1.2 on 2023-02-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_alter_servico_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='placa',
            field=models.CharField(max_length=8),
        ),
    ]
